# Generated by Django 5.0.6 on 2024-08-01 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_category_book'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='available_copies',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
