# Generated by Django 5.0.6 on 2024-08-01 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_borrow_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='borrow',
            name='borrow_count',
            field=models.IntegerField(default=0),
        ),
    ]
