# Generated by Django 5.0.6 on 2024-08-01 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_borrow_borrow_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='borrow',
            name='borrow_count',
            field=models.IntegerField(default=1),
        ),
    ]
