# Generated by Django 5.0.6 on 2024-08-02 10:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_ratingmodel_remove_book_user_reviews'),
    ]

    operations = [
        migrations.AddField(
            model_name='ratingmodel',
            name='book',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.book'),
        ),
    ]
