# Generated by Django 5.0.6 on 2024-08-02 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_ratingmodel_book'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ratingmodel',
            name='rate',
            field=models.IntegerField(),
        ),
    ]
