# Generated by Django 5.0.6 on 2024-08-02 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_remove_ratingmodel_book_ratingmodel_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ratingmodel',
            name='rate',
            field=models.CharField(choices=[('Poor', 'Poor'), ('Okay', 'Okay'), ('Good', 'Good'), ('Excellent', 'Excellent'), ('Outsatnding', 'Outsatnding')], max_length=100),
        ),
    ]
