# Generated by Django 5.0.6 on 2024-08-03 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_ratingmodel_book'),
    ]

    operations = [
        migrations.AddField(
            model_name='borrow',
            name='borrowing_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
